server.name: kibana
server.host: "0"
elasticsearch.url: http://es001:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
#elasticsearch.username: "elastic"
#elasticsearch.password: "changeme"