version: '3.4'
services:
  zoo001:
    image: 172.20.164.227:5000/zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo001
  zoo002:
    image: 172.20.164.227:5000/zookeeper:3.4
    ports:
    - "2182:2181"
    restart: always
    environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo002
  zoo003:
    image: 172.20.164.227:5000/zookeeper:3.4
    ports:
    - "2183:2181"
    restart: always
    environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo003
  zoo004:
    image: 172.20.164.227:5000/zookeeper:3.4
    ports:
    - "2184:2181"
    restart: always
    environment:
        ZOO_MY_ID: 4
        PEER_TYPE: observer            
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo004        
  broker001:
    image: 172.20.164.227:5000/wurstmeister/kafka:1.1.0 
    ports:
    - "9091:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003
      - zoo004           
    environment:
    - KAFKA_BROKER_ID=1        
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2181,zoo003:2181,zoo004:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker001:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.20.164.1:9091
    - KAFKA_AUTO_CREATE_TOPICS='enable'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker001
  broker002:
    image: 172.20.164.227:5000/wurstmeister/kafka:1.1.0 
    ports:
    - "9092:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003
      - zoo004           
    environment:
    - KAFKA_BROKER_ID=2        
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2181,zoo003:2181,zoo004:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker002:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.20.164.1:9092
    - KAFKA_AUTO_CREATE_TOPICS='enable'  
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker002
  broker003:
    image: 172.20.164.227:5000/wurstmeister/kafka:1.1.0 
    ports:
    - "9093:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003
      - zoo004           
    environment:
    - KAFKA_BROKER_ID=3      
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2181,zoo003:2181,zoo004:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker003:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.20.164.1:9093
    - KAFKA_AUTO_CREATE_TOPICS='enable'    
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker003               

  kafka-manager:
    image: 172.20.164.227:5000/sheepkiller/kafka-manager:1.3.0.4
    ports:
    - "9000:9000"
    restart: always
    environment:
    - ZK_HOSTS=zoo001:2181
    networks:
      backend:
        aliases:
        - kafka-manager      
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock     

  portainer:
    image: 172.20.164.227:5000/portainer/portainer
    ports:
      - "9001:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
          
networks:
  backend:
    external:
      name: backend