server.name: kibana
server.host: "0"
elasticsearch.url: http://10.164.201.27:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
#elasticsearch.username: "elastic"
#elasticsearch.password: "changeme"

i18n.defaultLocale: "ch"
