version: '3.4'
services:
  zoo001:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    networks:
      backend:
        aliases:
        - zoo001

  broker001:
    image: wurstmeister/kafka:1.1.0
    ports:
    - "9092:9092"
    environment:
    - KAFKA_HOST_NAME=broker001
    - KAFKA_ADVERTISED_HOST_NAME=broker001   
    - KAFKA_PORT=9092
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker001:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zoo001
    restart: always
    networks:
      backend:
        aliases:
        - broker001

networks:
  backend:
    external:
      name: backend