version: '3.4'
services:
  zoo001:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    networks:
      backend:
        aliases:
        - zoo001

  broker001:
    image: wurstmeister/kafka:1.1.0
    ports:
    - "9092:9092"
    environment:
    - KAFKA_HOST_NAME=broker001
    - KAFKA_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181
    - KAFKA_LISTENERS=PLAINTEXT://10.164.204.153:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zoo001
    restart: always
    networks:
      backend:
        aliases:
        - broker001

  kafka-manager:
    image: sheepkiller/kafka-manager:1.3.0.4
    ports:
    - "9000:9000"
    restart: always
    environment:
    - ZK_HOSTS=zoo001:2181
    networks:
      backend:
        aliases:
        - kafka-manager      
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock  

  portainer:
    image: portainer/portainer
    ports:
      - "9001:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    
networks:
  backend:
    external:
      name: backend