version: '2'
services:
  zoo001:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888   
    networks:
      backend:
        aliases:
        - zoo001
  zoo002:
    image: zookeeper:3.4
    ports:
    - "2182:2181"
    restart: always
    environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888  
    networks:
      backend:
        aliases:
        - zoo002
  zoo003:
    image: zookeeper:3.4
    ports:
    - "2183:2181"
    restart: always
    environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888  
    networks:
      backend:
        aliases:
        - zoo003     
  broker001:
    image: wurstmeister/kafka:1.1.0 
    ports:
    - "9091:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003          
    environment:
    - KAFKA_BROKER_ID=1         
    - KAFKA_HOST_NAME=broker001
    - KAFKA_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2181,zoo003:2181,zoo004:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker001:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9091
    - KAFKA_AUTO_CREATE_TOPICS='enable'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker001
  broker002:
    image: wurstmeister/kafka:1.1.0 
    ports:
    - "9092:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003          
    environment:
    - KAFKA_BROKER_ID=2      
    - KAFKA_HOST_NAME=broker002
    - KAFKA_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2181,zoo003:2181,zoo004:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker002:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_AUTO_CREATE_TOPICS='enable'    
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker002
  broker003:
    image: wurstmeister/kafka:1.1.0 
    ports:
    - "9093:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003          
    environment:
    - KAFKA_BROKER_ID=3      
    - KAFKA_HOST_NAME=broker003
    - KAFKA_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2181,zoo003:2181,zoo004:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker003:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9093
    - KAFKA_AUTO_CREATE_TOPICS='enable'    
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker003               

  kafka-manager:
    image: sheepkiller/kafka-manager:1.3.0.4
    ports:
    - "9000:9000"
    restart: always
    environment:
    - ZK_HOSTS=zoo001:2181
    networks:
      backend:
        aliases:
        - kafka-manager      
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock         
networks:
  backend:
    external:
      name: backend