version: '3'
services:
  es001:
    image: elasticsearch:6.4.0
    ports:
      - "9200:9200"
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./crack/x-pack-core-6.4.0.jar:/usr/share/elasticsearch/modules/x-pack-core/x-pack-core-6.4.0.jar
      - ./crack/license.json:/usr/share/elasticsearch/license.json
      - /data/esdata001:/usr/share/elasticsearch/data
    networks:
      backend:
        aliases:
          - es001

  kibana:
    image: kibana:6.4.0
    ports:
      - "5601:5601"
    restart: always
    networks:
      backend:
        aliases:
          - kibana
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es001

  logstash:
    image: logstash:6.4.0
    ports:
      - 9600:9600
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    volumes:
      - ./config/logstash.conf:/etc/logstash.conf
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      backend:
        aliases:
          - logstash
    depends_on:
      - es001
    entrypoint:
      - logstash
      - -f
      - /etc/logstash.conf
      - --config.reload.automatic
# docker network create -d=overlay --attachable backend
# docker network create --opt encrypted -d=overlay --attachable --subnet 10.10.0.0/16 backend


networks:
  backend:
    external:
      name: backend
