cluster.name: efk
node.name: es002
node.master: true
node.data: true
path:
  data:
    - /data/es003
    - /data/es004
network.host: es002
http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"

discovery.zen.ping.unicast.hosts: ["es001:9300", "es002:9300", "es003:9300"]
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping_timeout: 5s

bootstrap.memory_lock: true
action.destructive_requires_name: true
