version: '3.4'
services:
  zoo001:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo001
  zoo002:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo002
  zoo003:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo003
  zoo004:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    restart: always
    environment:
        ZOO_MY_ID: 4
        PEER_TYPE: observer            
        ZOO_SERVERS: server.1=zoo001:2888:3888 server.2=zoo002:2888:3888 server.3=zoo003:2888:3888 server.4=zoo004:2888:3888:observer    
    networks:
      backend:
        aliases:
        - zoo004        
  broker001:
    image: wurstmeister/kafka:1.1.0 
    ports:
    - "9091:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003
      - zoo004           
    environment:
    - KAFKA_BROKER_ID=1  
    - KAFKA_ADVERTISED_HOST_NAME=broker001
    - KAFKA_ADVERTISED_PORT=9092        
    - KAFKA_HOST_NAME=broker001
    - KAFKA_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2181,zoo003:2181,zoo004:2181
    - KAFKA_LISTENERS=PLAINTEXT://broker001:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker001:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker001
  broker002:
    image: wurstmeister/kafka:1.1.0 
    ports:
    - "9092:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003
      - zoo004           
    environment:
    - KAFKA_BROKER_ID=2      
    - KAFKA_ADVERTISED_HOST_NAME=broker002  
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_HOST_NAME=broker002
    - KAFKA_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2182,zoo003:2183,zoo004:2184
    - KAFKA_LISTENERS=PLAINTEXT://broker002:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker002:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker002
  broker003:
    image: wurstmeister/kafka:1.1.0 
    ports:
    - "9093:9092"
    restart: always
    depends_on:
      - zoo001
      - zoo002
      - zoo003
      - zoo004           
    environment:
    - KAFKA_BROKER_ID=3      
    - KAFKA_ADVERTISED_HOST_NAME=broker003  
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_HOST_NAME=broker003
    - KAFKA_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zoo001:2181,zoo002:2182,zoo003:2183,zoo004:2184
    - KAFKA_LISTENERS=PLAINTEXT://broker003:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker003:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
        - broker003               

networks:
  backend:
    external:
      name: backend