version: '3'
services:
  es001:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536        
    volumes:
      - ./config/es002.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/elasticsearch/data1:/data/elasticsearch/data1
      - /data/elasticsearch/data2:/data/elasticsearch/data2
      - /data/elasticsearch/data3:/data/elasticsearch/data3
      - /data/elasticsearch/log:/data/elasticsearch/log
      - /mount/es-snapshot-repo:/mount/es-snapshot-repo      